defaults: 
  - model: EGAT
  - optim: default
  - _self_

target: ""
experiment : QM9-node # name of the experiment, influences wandb run names, models and logs directories
dataset: QM9
num_workers : 0
cluster_num_workers :  8
deterministic : True
task_type: 2  # 1 property
              # 2 node
              # 3 edge
              # 4 property + node
              # 5 property + edge 
              # 6 node + edge
              # 7 property + node + edge

home_dir : C:/Users/tomma/Documents/Uni/Magistrale/Internship/Code
hydra:
  run:
    dir: ${home_dir}/MaMoMo/logs/${experiment}/${target}/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  project_name: MaMoMo-${experiment}-locale
  user: tcortecchia
  logdir : ${home_dir}/MaMoMo/logs/${experiment}/${target}

train: 
  do_bond_expansion: false
  compile: false
  spath : ${home_dir}/data
  dpath : ${home_dir}/MaMoMo/models/${experiment}/${target}
  sfilename: ${dataset}_graphs.bin
  splitfilename: ${dataset}_splits.json
  
  load_states: true
  statesfilename: ${dataset}_states.bin

  normalize: null # one of null, z_score, normalization, log
  infofile: ${dataset}_info.json

  load_and_split : true
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

  num_epochs: 1#500
  batch_size: 64

  es_patience: 32
  es_min_delta: 0.0001 

predict: 
  specify_checkpoint: False
  ckpt_path: null
  